version: '3.4'

services:
  webserver:
    image: nginx:alpine
    links:
      - crbc:app1
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDatabase
      MYSQL_USER: test
      MYSQL_PASSWORD: pwtest
    volumes:
      - ./init.sql/:/docker-entrypoint-initdb.d/init.sql
  crbc:
    build:
      context: ./CRBC
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    build:
      context: .
      dockerfile: CRBC/Dockerfile
